In [1]:
import pandas as pd

In [3]:
column_names=[
    'Class',
    'AGE',
    'SEX',
    'STEROID',
    'ANTIVIRALS',
    'FATIGUE',
    'MALAISE',
    'ANOREXIA',
    'LIVER BIG',
    'LIVER FIRM',
    'SPLEEN PALPABLE',
    'SPIDERS',
    'ASCITES',
    'VARICES',
    'BILIRUBIN',
    'ALK PHOSPHATE',
    'SGOT',
    'ALBUMIN',
    'PROTIME',
    'HISTOLOGY'
]
df=pd.read_csv('hepatitis.csv', header=None, names=column_names, index_col=False)
df.head()

,Class,AGE,SEX,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER BIG,LIVER FIRM,SPLEEN PALPABLE,SPIDERS,ASCITES,VARICES,BILIRUBIN,ALK PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY
0,2,30,2,1,2,2,2,2,1,2,2,2,2,2,1.00,85,18,4.0,?,1
1,2,50,1,1,2,1,2,2,1,2,2,2,2,2,0.90,135,42,3.5,?,1
2,2,78,1,2,2,1,2,2,2,2,2,2,2,2,0.70,96,32,4.0,?,1
3,2,31,1,?,1,2,2,2,2,2,2,2,2,2,0.70,46,52,4.0,80,1
4,2,34,1,2,2,2,2,2,2,2,2,2,2,2,1.00,?,200,4.0,?,1

In [4]:
df['SEX'].unique()

array([2, 1])

In [5]:
male_dataset=df[df['SEX']==1]
female_dataset=df[df['SEX']==2]

In [6]:
male_dataset.head()

,Class,AGE,SEX,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER BIG,LIVER FIRM,SPLEEN PALPABLE,SPIDERS,ASCITES,VARICES,BILIRUBIN,ALK PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY
1,2,50,1,1,2,1,2,2,1,2,2,2,2,2,0.90,135,42,3.5,?,1
2,2,78,1,2,2,1,2,2,2,2,2,2,2,2,0.70,96,32,4.0,?,1
3,2,31,1,?,1,2,2,2,2,2,2,2,2,2,0.70,46,52,4.0,80,1
4,2,34,1,2,2,2,2,2,2,2,2,2,2,2,1.00,?,200,4.0,?,1
5,2,34,1,2,2,2,2,2,2,2,2,2,2,2,0.90,95,28,4.0,75,1

In [7]:
female_dataset.head()

,Class,AGE,SEX,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER BIG,LIVER FIRM,SPLEEN PALPABLE,SPIDERS,ASCITES,VARICES,BILIRUBIN,ALK PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY
0,2,30,2,1,2,2,2,2,1,2,2,2,2,2,1.00,85,18,4.0,?,1
20,2,22,2,2,1,1,2,2,2,2,2,2,2,2,0.90,48,20,4.2,64,1
24,2,25,2,1,1,2,2,2,2,2,2,2,2,2,0.40,45,18,4.3,70,1
27,2,58,2,2,2,1,2,2,2,1,2,1,2,2,1.40,175,55,2.7,36,1
32,2,41,2,2,1,1,1,1,2,2,2,2,2,2,0.70,81,53,5.0,74,1

In [10]:
merged_dataset=pd.concat([male_dataset, female_dataset])
merged_dataset.head()

,Class,AGE,SEX,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER BIG,LIVER FIRM,SPLEEN PALPABLE,SPIDERS,ASCITES,VARICES,BILIRUBIN,ALK PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY
1,2,50,1,1,2,1,2,2,1,2,2,2,2,2,0.90,135,42,3.5,?,1
2,2,78,1,2,2,1,2,2,2,2,2,2,2,2,0.70,96,32,4.0,?,1
3,2,31,1,?,1,2,2,2,2,2,2,2,2,2,0.70,46,52,4.0,80,1
4,2,34,1,2,2,2,2,2,2,2,2,2,2,2,1.00,?,200,4.0,?,1
5,2,34,1,2,2,2,2,2,2,2,2,2,2,2,0.90,95,28,4.0,75,1

In [16]:
AGE_sorted_dataset=df.sort_values(by='AGE')

SGOT_sorted_dataset=df.sort_values(by='SGOT')

PROTIME_sorted_dataset=df.sort_values(by='PROTIME')

In [14]:
print(AGE_sorted_dataset.head())

     Class  AGE  SEX STEROID  ANTIVIRALS FATIGUE MALAISE ANOREXIA LIVER BIG  \
110      2    7    1       2           2       2       2        2         2
37       2   20    2       1           2       1       1        1         1
121      2   20    1       1           2       1       1        1         2
148      2   20    1       1           2       2       2        2         2
101      2   22    1       2           2       2       2        2         2

    LIVER FIRM SPLEEN PALPABLE SPIDERS ASCITES VARICES BILIRUBIN  \
110          1               1       2       2       2      0.70
37           1               1       1       2       2      2.30
121          2               2       1       1       2      1.00
148          ?               2       2       2       2      0.90
101          2               2       2       2       2      0.70

    ALK PHOSPHATE SGOT ALBUMIN PROTIME  HISTOLOGY
110           256   25     4.2       ?          2
37            150   68     3.9       ?          1
121           160  118     2.9      23          2
148            89  152     4.0       ?          2
101             ?   24       ?       ?          2

In [15]:
print(SGOT_sorted_dataset.head())

     Class  AGE  SEX STEROID  ANTIVIRALS FATIGUE MALAISE ANOREXIA LIVER BIG  \
74       2   50    1       2           2       2       2        2         2
131      1   31    1       1           2       1       1        1         2
45       2   28    1       2           2       1       1        2         2
144      1   45    1       2           2       1       1        1         2
90       2   50    2       1           2       1       2        2         1

    LIVER FIRM SPLEEN PALPABLE SPIDERS ASCITES VARICES BILIRUBIN  \
74           2               2       2       2       2      1.50
131          2               1       2       2       2      8.00
45           2               2       2       2       2      0.70
144          2               2       1       1       2      1.90
90           1               1       1       2       2      0.90

    ALK PHOSPHATE SGOT ALBUMIN PROTIME  HISTOLOGY
74            100  100     5.3       ?          1
131             ?  101     2.2       ?          2
45             74  110     4.4       ?          1
144             ?  114     2.4       ?          2
90            230  117     3.4      41          2

In [17]:
print(PROTIME_sorted_dataset.head())

     Class  AGE  SEX STEROID  ANTIVIRALS FATIGUE MALAISE ANOREXIA LIVER BIG  \
130      2   54    1       2           2       2       2        2         2
53       2   40    1       2           1       1       2        2         2
28       2   61    1       1           2       1       2        2         1
25       2   27    1       1           2       1       1        2         2
60       2   37    1       2           2       2       2        2         2

    LIVER FIRM SPLEEN PALPABLE SPIDERS ASCITES VARICES BILIRUBIN  \
130          2               2       2       2       2      1.00
53           1               1       2       2       2      1.20
28           1               2       2       2       2      1.30
25           2               2       2       2       2      0.80
60           2               2       2       2       2      0.70

    ALK PHOSPHATE SGOT ALBUMIN PROTIME  HISTOLOGY
130            85   30     4.5       0          2
53             85   31     4.0     100          1
28             78   25     3.8     100          1
25             95   46     3.8     100          1
60             26   58     4.5     100          1

In [19]:
transposed_dataset=df.transpose()
transposed_dataset.head()

,0,1,2,3,4,5,6,7,8,9,...,145,146,147,148,149,150,151,152,153,154
Class,2,2,2,2,2,2,1,2,2,2,...,2,1,1,2,2,1,2,2,2,1
AGE,30,50,78,31,34,34,51,23,39,30,...,31,41,70,20,36,46,44,61,53,43
SEX,2,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,2,1
STEROID,1,1,2,?,2,2,1,2,2,2,...,1,2,1,1,2,2,2,1,1,2
ANTIVIRALS,2,2,2,1,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2

In [20]:
df.head()

,Class,AGE,SEX,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER BIG,LIVER FIRM,SPLEEN PALPABLE,SPIDERS,ASCITES,VARICES,BILIRUBIN,ALK PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY
0,2,30,2,1,2,2,2,2,1,2,2,2,2,2,1.00,85,18,4.0,?,1
1,2,50,1,1,2,1,2,2,1,2,2,2,2,2,0.90,135,42,3.5,?,1
2,2,78,1,2,2,1,2,2,2,2,2,2,2,2,0.70,96,32,4.0,?,1
3,2,31,1,?,1,2,2,2,2,2,2,2,2,2,0.70,46,52,4.0,80,1
4,2,34,1,2,2,2,2,2,2,2,2,2,2,2,1.00,?,200,4.0,?,1

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155 entries, 0 to 154
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Class            155 non-null    int64
 1   AGE              155 non-null    int64
 2   SEX              155 non-null    int64
 3   STEROID          155 non-null    object
 4   ANTIVIRALS       155 non-null    int64
 5   FATIGUE          155 non-null    object
 6   MALAISE          155 non-null    object
 7   ANOREXIA         155 non-null    object
 8   LIVER BIG        155 non-null    object
 9   LIVER FIRM       155 non-null    object
 10  SPLEEN PALPABLE  155 non-null    object
 11  SPIDERS          155 non-null    object
 12  ASCITES          155 non-null    object
 13  VARICES          155 non-null    object
 14  BILIRUBIN        155 non-null    object
 15  ALK PHOSPHATE    155 non-null    object
 16  SGOT             155 non-null    object
 17  ALBUMIN          155 non-null    object
 18  PROTIME          155 non-null    object
 19  HISTOLOGY        155 non-null    int64
dtypes: int64(5), object(15)
memory usage: 24.3+ KB

In [27]:
melted_dataset=pd.melt(
    df,
    id_vars='SEX',
    value_vars=[
        'AGE',
        'Class',
        'ANTIVIRALS'
    ],
    var_name='Attributes',
    value_name='Values'
)
melted_dataset.head()

   SEX Attributes  Values
0    2        AGE      30
1    1        AGE      50
2    1        AGE      78
3    1        AGE      31
4    1        AGE      34

In [28]:
wide_format=melted_dataset.pivot_table(
    index='SEX',
    columns='Attributes',
    values='Values',
    aggfunc='mean'
)
wide_format.head()

Attributes        AGE  ANTIVIRALS     Class
SEX
1           41.165468    1.856115  1.769784
2           41.500000    1.750000  2.000000